#!/usr/bin/env bash
# ship-project.sh — `ship project`: take what the swarm has already finished in
# a product checkout and stop at a reviewable PR.
#
# WHY A SECOND SHIPPING VERB. `run issue` ships one issue that IT dispatched:
# it created the branch, posted the task, and knows the single task name to
# accept. Upstream's lieutenant forge dispatches instead — the operator cuts
# cards in the dashboard or the chat rail, the lieutenant moves them through
# `.swarmforge/routes.tsv`, and nothing here created a branch or knows a task
# name in advance. Upstream then stops dead: its work lifecycle ends at "the
# board moves the card to Done". There is no `git push` and no `gh pr` anywhere
# in its prompts, scripts or docs, and `lieutenant.prompt` is explicitly denied
# every git verb it might otherwise reach for. The last mile is outside the
# forge by design, and this verb is that last mile for lieutenant-dispatched
# work. `run issue` is untouched and still owns the issue-per-branch shape.
#
# WHAT IT SHIPS. Whatever terminal handoffs the master worktree has accepted
# and `origin/<base>` does not already carry — `accept-work.sh`'s report, run
# as-is rather than re-derived here. Cards, not commits, are the unit a human
# reasons about, and that script already owns the two hard parts: reading the
# terminal record out of the master worktree only, and excluding a task whose
# commit already reached origin.
#
# THE GATE THAT EARNS ITS KEEP. A Done card and a merged product checkout are
# two different events. `handoffd` marks the card `done` when it DELIVERS the
# terminal handoff; the master merges it some time after that. Ship in that
# window and `git log origin/base..HEAD` quietly carries a SUBSET of the work —
# a PR that looks complete and is missing a card. So every delivery record's
# commit is checked for ancestry in HEAD, and a miss is a blocker, never a
# shrug.
#
# It never merges the PR, never force-pushes, never commits for you, and never
# pushes from a role worktree under .worktrees/.
#
# TWO PASSES, same shape as `run issue`: the first pass reports, gates, creates
# the branch and pushes it, then stops at NEEDS_PR_BODY (exit 8) because the
# prose belongs to something that read the diff. Send a subagent with the
# `to-pr` skill, then re-run with --body-file. --dry-run stops before the push
# when you want the report alone.
#
# Exit codes / STATUS line:
#   0 PR_OPENED   0 NOTHING_TO_SHIP   0 DRY_RUN   2 USAGE   5 ERROR
#   6 BLOCKED     8 NEEDS_PR_BODY
# BLOCKED is 6 for the same reason run-issue.sh uses 6: a refusal on evidence
# is not a failure of the verb, and nothing was changed. NOTHING_TO_SHIP and
# DRY_RUN are 0 because both are the verb doing exactly what was asked; the
# STATUS word, not the code, is what tells them apart. Contract details live in
# ../SKILL.md (verb: ship project).
#
# Usage: ship-project.sh --root <product-root> \
#   [--target user@host] [--key <path>] [--local] \
#   [--branch <name>] [--base <name>] [--test-cmd <cmd>] [--issue <N>]... \
#   [--body-file <path>] [--dry-run]
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
. "$HERE/lib-wake-talk.sh"

TARGET=${TARGET:-admin@100.64.0.4}
KEY=${KEY:-$HOME/.ssh/tailscale_key}
ROOT='' LOCAL=0 BRANCH='' BASE='' TEST_CMD='' BODY_FILE='' DRY_RUN=0
ISSUES=''

# Usage text is grepped, not line-numbered: offsets rot on the first comment
# edit, and a usage message that prints the wrong lines is worse than none.
usage() { sed -n '/^# Usage: ship-project.sh/,/^set -euo/p' "$0" | sed '$d'; }

while [ $# -gt 0 ]; do
  case $1 in
    --root) ROOT=$2; shift 2 ;;
    --target) TARGET=$2; shift 2 ;;
    --key) KEY=$2; shift 2 ;;
    --local) LOCAL=1; shift ;;
    --branch) BRANCH=$2; shift 2 ;;
    --base) BASE=$2; shift 2 ;;
    --test-cmd) TEST_CMD=$2; shift 2 ;;
    --issue) ISSUES="${ISSUES}${ISSUES:+ }${2#\#}"; shift 2 ;;
    --body-file) BODY_FILE=$2; shift 2 ;;
    --dry-run) DRY_RUN=1; shift ;;
    *) usage; exit 2 ;;
  esac
done
[ -n "$ROOT" ] || { usage; exit 2; }
ROOT=${ROOT%/}

run_remote() {
  if [ "$LOCAL" = 1 ]; then bash -c "$1"
  else ssh -i "$KEY" "$TARGET" "$1"; fi
}
in_root() { run_remote "cd '$ROOT' && $1"; }

PROJECT=$(basename "$ROOT")
BLOCKERS=''
block() { BLOCKERS="${BLOCKERS}${BLOCKERS:+$'\n'}- $1"; }

# ---------- gate A: is this a product checkout at all ----------
# Three ways to point this verb at something that must never be pushed, each
# with its own message because the fix differs. A role worktree is a generated
# checkout on a `swarmforge-<name>` branch; a forge root holds projects/ and is
# not a product repo at all; a subdirectory would push the whole repo while
# reporting a path that is not its root.
case "$ROOT" in
  */.worktrees/*) die BLOCKED "$ROOT is a role worktree — .worktrees/* is generated by SwarmForge and is never the publish source; point --root at the product checkout (the master worktree)" 6 ;;
esac
if run_remote "test -d '$ROOT/projects' && test -e '$ROOT/swarm'" 2>/dev/null; then
  die BLOCKED "$ROOT looks like a forge root (it has projects/ and swarm) — the product repo is projects/<name>; point --root there" 6
fi
TOP=$(in_root "git rev-parse --show-toplevel" 2>/dev/null) \
  || die ERROR "$ROOT is not a git work tree (or the target is unreachable)" 5
TOP=${TOP%$'\n'}
# Compared against the RESOLVED root, not the string that was typed: git
# answers with symlinks resolved (/tmp is /private/tmp on macOS), so a literal
# comparison refuses a perfectly good product root whenever any path component
# is a symlink.
ROOT_REAL=$(in_root "pwd -P" 2>/dev/null || printf '%s' "$ROOT")
ROOT_REAL=${ROOT_REAL%$'\n'}
[ "$TOP" = "$ROOT_REAL" ] \
  || die BLOCKED "$ROOT is inside a repo whose root is $TOP — run this verb at the repo root so the report and the push describe the same tree" 6

MISSION=''
if MISSION_RAW=$(read_file mission.md 2>/dev/null); then
  MISSION=$(printf '%s\n' "$MISSION_RAW" | awk 'NF { print; exit }')
fi

# ---------- gate B: the board ----------
# tasks.tsv, not the dashboard: pack_web binds a fresh port on every start and
# may not be running at all when a human decides to ship. Columns are
# name, lane, created, updated, task-id, audit-count, type (card_type.bb's
# format-row) — lane has been column 2 across every version of the board.
#
# `waiting` is reported, never blocking. A waiting card is a card the
# lieutenant has not started; the plan not being finished is not a reason to
# refuse to publish the part that is. A card in a ROLE lane is blocking: work
# is in flight and shipping now cuts it in half.
BOARD=$(read_file .swarmforge/board/tasks.tsv 2>/dev/null || true)
LIVE=$(printf '%s\n' "$BOARD" | awk -F'\t' 'NF && $2 != "done" && $2 != "waiting" { printf "%s (%s) ", $1, $2 }')
DONE_N=$(printf '%s\n' "$BOARD" | awk -F'\t' '$2 == "done"' | wc -l | tr -d ' ')
WAIT_N=$(printf '%s\n' "$BOARD" | awk -F'\t' '$2 == "waiting"' | wc -l | tr -d ' ')
LIVE_N=$(printf '%s\n' "$BOARD" | awk -F'\t' 'NF && $2 != "done" && $2 != "waiting"' | wc -l | tr -d ' ')
[ -z "$LIVE" ] || block "board has live cards: ${LIVE% }"

# ---------- gate C: failed deliveries ----------
# A delivery that failed and stayed failed means a chain that never closed;
# publishing over one publishes a tree that is missing a hop.
#
# TWO paths are checked because the two SwarmForge lineages name this-same
# thing differently, and a gate that looks at only one of them is a gate that
# cannot fire on the other:
#
#   handoffs/*/failed/       handoffd.bb's fail! moves a permanently failed
#                            handoff here, per worktree. This is what the
#                            main-lineage code in this repository actually
#                            writes, and it is the one that fires today.
#   .swarmforge/delivery_attention/
#                            the lieutenant lineage's name for the same state.
#                            Absent here, kept so this gate keeps working after
#                            that branch is synced.
#
# Checking only delivery_attention/ was the bug: on this repository's own code
# that directory is never created, so the gate silently passed every time.
FAILED=$(run_remote "ls -1 '$ROOT'/.swarmforge/handoffs/failed '$ROOT'/.worktrees/*/.swarmforge/handoffs/failed '$ROOT/.swarmforge/delivery_attention' 2>/dev/null | grep -v '^$' | grep -v ':$' | head -20" || true)
ATTENTION_LINE=none
if [ -n "$FAILED" ]; then
  ATTENTION_LINE=$(printf '%s' "$FAILED" | tr '\n' ' ')
  block "failed deliveries are not cleared: $ATTENTION_LINE"
fi

# ---------- gate D: git hygiene ----------
# Uncommitted changes block rather than get committed for you. What is in the
# working tree of a product checkout after a swarm run is either a role's
# leftover or a human's edit, and neither belongs in a PR nobody reviewed.
DIRTY=$(git_status "$ROOT" || true)
[ -z "$DIRTY" ] || block "uncommitted changes in $ROOT: $(printf '%s' "$DIRTY" | tr '\n' ';' )"

in_root "git fetch origin --quiet" >/dev/null 2>&1 \
  || block "git fetch origin failed — cannot compare against the remote"
if [ -z "$BASE" ]; then
  for candidate in main master; do
    if in_root "git rev-parse --verify --quiet $(printf '%q' "refs/remotes/origin/$candidate")" >/dev/null 2>&1; then
      BASE=$candidate; break
    fi
  done
fi
[ -n "$BASE" ] || die ERROR "no origin/main or origin/master in $ROOT and no --base given — add a remote first (gh repo create / git remote add)" 5

HEAD_SHA=$(in_root "git rev-parse --short HEAD") || die ERROR "cannot read HEAD in $ROOT" 5
HEAD_SHA=${HEAD_SHA%$'\n'}
BASE_SHA=$(in_root "git rev-parse --short $(printf '%q' "origin/$BASE")" 2>/dev/null || true)
BASE_SHA=${BASE_SHA%$'\n'}
AHEAD=$(in_root "git rev-list --count $(printf '%q' "origin/$BASE")..HEAD" 2>/dev/null || echo 0)
AHEAD=${AHEAD%$'\n'}
# Behind is reported, never blocking. `run issue` refuses a stale BASE because
# it is about to START work there, and building on stale code is the whole
# cost. Here the work is already finished, so refusing would strand it. The PR
# is still correct either way (GitHub diffs against the merge-base); what the
# operator needs to know is that the swarm built against a base that has since
# moved — the same "nobody ran git pull after the merge" trap in its second
# disguise, arriving through the Dashboard instead of through run issue.
BEHIND=$(in_root "git rev-list --count HEAD..$(printf '%q' "origin/$BASE")" 2>/dev/null || echo 0)
BEHIND=${BEHIND%$'\n'}
COMMITS=$(in_root "git log --oneline $(printf '%q' "origin/$BASE")..HEAD" 2>/dev/null || true)

# ---------- what is being shipped ----------
# accept-work.sh is run, not reimplemented: it already resolves the terminal
# record from the master worktree only and already drops tasks whose commit
# reached origin. Its report is STATUS, then WARN= lines, then one
# task/commit/completed_at block per unshipped task — read by prefix, never by
# line offset, because a WARN shifts every offset.
AW_ARGS=(--root "$ROOT")
if [ "$LOCAL" = 1 ]; then AW_ARGS+=(--local); else AW_ARGS+=(--target "$TARGET" --key "$KEY"); fi
AW=$("$HERE/accept-work.sh" "${AW_ARGS[@]}") \
  || die ERROR "accept work failed for $ROOT — cannot resolve what is unshipped" 5
CARDS=$(printf '%s\n' "$AW" | awk '
  index($0, "task: ") == 1 { task = substr($0, 7); next }
  index($0, "commit: ") == 1 && task != "" { print task "\t" substr($0, 9); task = "" }')
AW_WARN=$(printf '%s\n' "$AW" | grep '^WARN=' || true)

# The window this verb exists to refuse: the board says done, the delivery
# record exists, and the commit has not reached the product HEAD yet because
# the master is still merging it. Shipping here loses a card silently.
MISSING='' CARD_ISSUES=''
while IFS=$'\t' read -r task commit; do
  [ -n "${commit:-}" ] || continue
  in_root "git merge-base --is-ancestor $(printf '%q' "$commit") HEAD" >/dev/null 2>&1 \
    || MISSING="${MISSING}${MISSING:+, }$task ($commit)"
  # The card text is what the operator typed into New Task, and it carries the
  # issue number. Only the cards BEING SHIPPED are read, never the whole board:
  # a card that is not in this PR must not put a Closes line in it.
  CARD_ISSUES="$CARD_ISSUES $(run_remote "grep -o '#[0-9][0-9]*' $(printf '%q' "$ROOT/.swarmforge/board/$task.txt") 2>/dev/null" | tr -d '#' | tr '\n' ' ' || true)"
done <<< "$CARDS"
CARD_ISSUES=$(printf '%s\n' $CARD_ISSUES | sort -un | tr '\n' ' ')
CARD_ISSUES=${CARD_ISSUES% }
[ -z "$MISSING" ] || block "delivered but not in HEAD yet — the master is still merging, re-run in a moment: $MISSING"

# ---------- gate E: tests ----------
# Discovery, not configuration: a project that has a test entry point gets it
# run, a project that does not says so in the report and in the PR. A red suite
# blocks with no override flag — an override would be used exactly once, on the
# day it mattered.
TESTS_CMD=$TEST_CMD
if [ -z "$TESTS_CMD" ]; then
  if in_root "test -f Makefile && grep -q '^test:' Makefile" >/dev/null 2>&1; then TESTS_CMD='make test'
  elif in_root "test -f package.json && grep -q '\"test\"[[:space:]]*:' package.json" >/dev/null 2>&1; then TESTS_CMD='npm test'
  elif in_root "test -f pytest.ini || test -f pyproject.toml" >/dev/null 2>&1; then TESTS_CMD='pytest -q'
  elif in_root "test -x ./gradlew" >/dev/null 2>&1; then TESTS_CMD='./gradlew test'
  fi
fi
if [ -n "$BLOCKERS" ]; then
  TESTS_RESULT='not run (blocked earlier)'
elif [ -z "$TESTS_CMD" ]; then
  TESTS_RESULT='skipped (no test entry point found)'
elif in_root "$TESTS_CMD" >/dev/null 2>&1; then
  TESTS_RESULT='pass'
else
  TESTS_RESULT='FAIL'
  block "tests failed: $TESTS_CMD — run it yourself in $ROOT to see the output"
fi

# Three sources, none of them a guess, merged and deduplicated:
#   --issue N        the caller says it. Always available, always wins nothing
#                    and loses nothing — it is just another number in the set.
#   card text        `#<digits>` in what the operator typed into New Task.
#   card name        the exact `issue-<N>-<slug>` shape run-issue.sh mints.
# The card-NAME match stays exact rather than becoming a scan, because the name
# is derived, not typed. The card TEXT is typed by a human who is looking at
# the issue, which is what makes scanning it fair game here and not there.
closes_numbers() {
  { printf '%s\n' "$CARDS" | awk -F'\t' '
      match($1, /^issue-[0-9]+-/) { print substr($1, 7, RLENGTH - 7) }'
    printf '%s\n' $ISSUES $CARD_ISSUES
  } | { grep -E '^[0-9]+$' || true; } | sort -un
}

[ -n "$BRANCH" ] || BRANCH="feat/swarm-$PROJECT-$(date -u +%Y%m%d)"
TITLE="[swarm] $PROJECT: $(printf '%s\n' "$CARDS" | awk -F'\t' 'NF { print $1; exit }')"
[ "$TITLE" != "[swarm] $PROJECT: " ] || TITLE="[swarm] $PROJECT: ${MISSION:-published from the swarm board}"

# ---------- the report ----------
# Printed on every path, including the blocked one: the reason to refuse is
# only useful next to the state it was read from.
report() {
  printf 'project: %s\npath: %s\nmission: %s\nboard: done %s / waiting %s / live %s\nfailed deliveries: %s\nbase: origin/%s @ %s\nhead: %s (ahead %s, behind %s)\n' \
    "$PROJECT" "$ROOT" "${MISSION:-<no mission.md>}" "$DONE_N" "$WAIT_N" "$LIVE_N" \
    "$ATTENTION_LINE" "$BASE" "${BASE_SHA:-<unknown>}" "$HEAD_SHA" "$AHEAD" "$BEHIND"
  [ "${BEHIND:-0}" = 0 ] \
    || printf 'WARN=the swarm built on a base that has moved: HEAD is %s commits behind origin/%s\n' \
         "$BEHIND" "$BASE"
  printf 'cards to ship:\n'
  if [ -n "$CARDS" ]; then
    printf '%s\n' "$CARDS" | awk -F'\t' 'NF { printf "  %s  %s\n", $2, $1 }'
  else
    printf '  (none)\n'
  fi
  printf 'commits to ship:\n'
  if [ -n "$COMMITS" ]; then printf '%s\n' "$COMMITS" | sed 's/^/  /'
  else printf '  (none)\n'; fi
  printf 'tests: %s%s\n' "${TESTS_CMD:-<none>}" " -> $TESTS_RESULT"
  # Printed BEFORE the PR is opened, on the pass that stops at NEEDS_PR_BODY,
  # so the operator sees exactly which issues are about to be closed while
  # there is still a pass left to drop a wrong one with --branch/--issue.
  WILL_CLOSE=$(closes_numbers | tr '\n' ' '); WILL_CLOSE=${WILL_CLOSE% }
  printf 'will close: %s\n' "${WILL_CLOSE:-none}"
  printf 'branch: %s\ntitle: %s\n' "$BRANCH" "$TITLE"
  [ -z "$AW_WARN" ] || printf '%s\n' "$AW_WARN"
}

if [ -n "$BLOCKERS" ]; then
  printf 'STATUS=BLOCKED\n'
  report
  printf 'blockers:\n%s\n' "$BLOCKERS"
  exit 6
fi

if [ -z "$CARDS" ] || [ "$AHEAD" = 0 ]; then
  printf 'STATUS=NOTHING_TO_SHIP\n'
  report
  printf 'nothing was pushed: %s\n' \
    "$([ -z "$CARDS" ] && echo 'accept work reports no unshipped delivery record' || echo "HEAD is not ahead of origin/$BASE")"
  exit 0
fi

if [ "$DRY_RUN" = 1 ]; then
  printf 'STATUS=DRY_RUN\n'
  report
  printf 'nothing was pushed and no branch was created; re-run without --dry-run\n'
  exit 0
fi

# ---------- push ----------
# The branch is created AT HEAD without checking it out. The product checkout
# stays on the branch the swarm left it on, and the role worktrees under
# .worktrees/ keep their own `swarmforge-<name>` branches — a checkout here
# would move the tree under running agents.
in_root "git rev-parse --verify --quiet $(printf '%q' "refs/heads/$BRANCH")" >/dev/null 2>&1 \
  || in_root "git branch $(printf '%q' "$BRANCH") HEAD" \
  || die ERROR "could not create $BRANCH at HEAD in $ROOT" 5
in_root "git push -u origin $(printf '%q' "$BRANCH")" \
  || die ERROR "could not push $BRANCH from $ROOT — the branch exists locally; re-run to continue" 5

# Same idempotency as run-issue.sh, and for the same reason: a run killed
# between the push and the PR must not open a second PR for the same head. The
# check runs BEFORE the body is required so a resume never costs a model call.
PR_URL=$(in_root "gh pr list --head $(printf '%q' "$BRANCH") --state open --json url --jq '.[].url' | head -1") \
  || PR_URL=''
PR_URL=${PR_URL%$'\n'}

if [ -z "$PR_URL" ]; then
  if [ -z "$BODY_FILE" ]; then
    printf 'STATUS=NEEDS_PR_BODY\n'
    report
    printf 'the branch is pushed and no PR is open. Write the body for origin/%s..%s, then re-run the same command with --body-file <path>. Send a subagent with the to-pr skill: the diff belongs in that subagent, not in yours. Do not write the card list or Closes lines — this verb appends them.\n' \
      "$BASE" "$BRANCH"
    exit 8
  fi
  [ -f "$BODY_FILE" ] \
    || die ERROR "--body-file $BODY_FILE does not exist; $BRANCH is pushed and no PR was opened" 5
  PR_PROSE=$(cat "$BODY_FILE")
  [ -n "$(printf '%s' "$PR_PROSE" | tr -d '[:space:]')" ] \
    || die ERROR "--body-file $BODY_FILE is empty; refusing to open a PR with no body. $BRANCH is pushed, no PR was opened" 5

  # `Closes #N` has TWO sources, and neither of them guesses.
  #
  # --issue is the one that matters in practice. Most cards are cut straight
  # from the Dashboard by the operator or the lieutenant, which means the card
  # name is free text and the issue number lives only in the head of whoever
  # cut it. That person is the caller, so the caller says it.
  #
  # The card-name derivation stays for the cards run-issue.sh minted, where
  # `issue-<N>-<slug>` IS the issue number and reading it costs nothing. It is
  # an exact-shape match, never a scan for `#<digits>`: a loose scan would find
  # a PR number or a `#1 priority` in card text and close the wrong issue,
  # which is worse than closing none.
  CLOSES=$(closes_numbers | sed 's/^/Closes #/')
  CARD_LINES=$(printf '%s\n' "$CARDS" | awk -F'\t' 'NF { printf "- %s (%s)\n", $1, $2 }')
  STALE_LINE=''
  [ "${BEHIND:-0}" = 0 ] || STALE_LINE=$(printf -- '- NOTE: this work was built on a base that has since moved; HEAD is %s commits behind origin/%s\n' "$BEHIND" "$BASE")
  PR_BODY=$(printf '%s%s\n\n---\n\n## Cards shipped\n%s\n\n## Verification\n- tests: %s -> %s\n- board: done %s / waiting %s / live %s, no failed deliveries outstanding\n- published from the managed project checkout %s at %s; no role worktree was used as the push source\n%s' \
    "${CLOSES:+$CLOSES$'\n\n'}" "$PR_PROSE" "$CARD_LINES" \
    "${TESTS_CMD:-<none>}" "$TESTS_RESULT" "$DONE_N" "$WAIT_N" "$LIVE_N" "$ROOT" "$HEAD_SHA" \
    "$STALE_LINE")

  PR_OUT=$(in_root "gh pr create --base $(printf '%q' "$BASE") --head $(printf '%q' "$BRANCH") --title $(printf '%q' "$TITLE") --body $(printf '%q' "$PR_BODY")") \
    || die ERROR "gh pr create failed for $BRANCH -> $BASE in $ROOT" 5
  PR_URL=$(printf '%s\n' "$PR_OUT" | grep -o 'https://[^[:space:]]*' | tail -1 || true)
  [ -n "$PR_URL" ] || die ERROR "gh pr create returned no PR URL: $PR_OUT" 5
fi

printf 'STATUS=PR_OPENED\n'
report
printf 'url: %s\n' "$PR_URL"
exit 0
